version: "3"

services:
  nextjs:
    build: .
    container_name: next-dev
    ports:
      - "3060:3060"
    volumes:
      - .:/app
      - /app/node_modules  # impede que os node_modules locais sobrescrevam os do container
    environment:
      - NODE_ENV=development
    command: npm run dev